# Generated by Django 5.1.6 on 2025-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_alter_product_uuid_alter_purchaseorder_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_address',
            field=models.TextField(default='asdasdasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_name',
            field=models.CharField(default='abcasd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to_phone',
            field=models.CharField(default='asdasddas', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_address',
            field=models.TextField(default='dasdas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_email',
            field=models.EmailField(default='istiaqhasan93@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_name',
            field=models.CharField(default='asdas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company_phone',
            field=models.CharField(default='asdas', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_location',
            field=models.TextField(default='efrwef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manager_name',
            field=models.CharField(default='dddd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='md_name',
            field=models.CharField(default='fff', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.TextField(default='ddad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='qtn_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subject',
            field=models.CharField(default='dddddd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subject_description',
            field=models.TextField(default='ddd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_and_conditions',
            field=models.TextField(default='ddd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_in_words',
            field=models.CharField(default='dddd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
            preserve_default=False,
        ),
    ]
